# 한글 깨짐 현상 방지
server:
  servlet:
    encoding:
      force-response: true
  port: 8081

spring:
  # DB 연결 정보
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url, username, password는 환경변수로 등록
    url: url
    username: username
    password: password
    # 배치 사이즈 조정에 필요
    #hikari:
    #  data-source-properties:
    #    rewriteBatchedStatements: true

  # JPA 설정
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
    # 배치 사이즈 조정
    #properties:
    #  hibernate:
    #    jdbc:
    #      batch_size: 111942
    #      order_inserts: true
    #      order_updates: true

  # PUT, DELETE 가능하게 해줌
  mvc:
    hiddenmethod:
      filter:
        enabled: true